### ISSUE TITLE
Cannot set property 'options' of undefined

### ISSUE THREAD

**Issue by AndrewMonty** [slickplaid/node-slack-mailgun#1]
Trying to get this working on a vagrant box with a centos image

```
cd /var/www
mkdir slackgun
cd slackgun
npm init
..
npm install express --save
npm install node-slack-mailgun --save
```

```
// app.js
var SlackGun = require('node-slack-mailgun');
var slack_hook_url = 'foo';
var mailgun_apikey = 'bar';
var express = require('express');

var app = express();

app.use('/api/mailgun', SlackGun({
    slack: {
        hook: slack_hook_url,
        channel: 'dev_bad_notifications'
    },
    mailgun: { apikey: mailgun_apikey }
}));
```

```
$ node app.js

/var/www/slackgun/node_modules/node-slack-mailgun/index.js:31
        that.options = getOptions(options);
                     ^
TypeError: Cannot set property 'options' of undefined
    at SlackGun (/var/www/slackgun/node_modules/node-slack-mailgun/index.js:31:15)
    at Object.<anonymous> (/var/www/slackgun/app.js:8:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

`this` in the SlackGun function is undefined. I'm pretty sure I set everything up correctly, not sure what's going wrong.

**Comment by slickplaid** [comment]
Hey Andrew, let me take a look at this issue and get back with you.

**Comment by slickplaid** [comment]
What version of Node and Express are you using?

**Comment by AndrewMonty** [comment]
node v0.10.36
express 4.13.4

**Comment by slickplaid** [comment]
e18ac8a0e3faa1b45cbb2e5d147486e3e42aa1dd should fix this bug. Pushing to npm now.

**Comment by slickplaid** [comment]
Pushed v0.7.2 to npm

**Comment by slickplaid** [comment]
Closing issue. If you still have problems, let me know.
